credentials:
  usernames:
    arshdeep@gmail.com:
      email: arshdeep@gmail.com
      name: Arshdeep
      password: arshdeep1
    jasmeet@bettrearth.com:
      email: jasmeet@gmail.com
      name: Jasmeet
      password: jasmeet2
cookie:
  expiry_days: 10
  key: bettr_earth_store_app
  name: BE Store
  
preauthorized:
  emails:
  - test@bettrearth.com
